# Generated by Django 4.0.2 on 2022-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='file',
            field=models.FileField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
